name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang cmake gcc

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_SANITIZER=ON

      - name: Build
        run: cmake --build build -j $(nproc)

      - name: Run unit tests
        run: build/test/unit_test

      - name: Run ASan example
        run: ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 build/src/prsh examples/hello_world.json

      - name: Run UBSan example
        run: UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1 build/src/prsh examples/hello_world.json
